# Generated by Django 4.0.3 on 2022-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
